NetworksLabsCsvReaderBundle_homepage:
    pattern:  /
    defaults: { _controller: NetworksLabsCsvReaderBundle:Default:index }

NetworksLabsCsvReaderBundle_verif:
    pattern:  /verif
    defaults: { _controller: NetworksLabsCsvReaderBundle:Default:verif }


NetworksLabsCsvReaderBundle_delete:
    pattern:  /delete/{import_key}
    defaults: { _controller: NetworksLabsCsvReaderBundle:Default:delete }


NetworksLabsCsvReaderBundle_ajax:
    pattern:  /ajax/{import_key}
    defaults: { _controller: NetworksLabsCsvReaderBundle:Default:ajax }


NetworksLabsCsvReaderBundle_import:
    pattern:  /{import_key}
    defaults: { _controller: NetworksLabsCsvReaderBundle:Default:import }


