parameters:
    networks_labs_csv_reader.class: NetworksLabs\CsvReaderBundle\Reader\Reader

services:
    networks_labs_csv_reader:
        class: %networks_labs_csv_reader.class%
        arguments: [%networks_labs_csv_reader%]
    #networks_labs_gallery.twig.extension:
        #class: %twig.extension.class%
        #arguments: [@service_container]
        #tags:
            #- { name: twig.extension }
